### ISSUE TITLE
Progress bar in startup

### ISSUE THREAD

**Issue by posikifi** [nls-oskari/oskari#10]
Hi,

I suggest that you add progress bar to startup. Personally I have had some problems when I wait with older machine and with low bandwidth connection to wait that all necessary javascript files are uploaded and runned.

Maybe you can even add "status" field in the below of the UI, where you can put messages for users/developers. Or maybe it there already..

P

**Comment by nls-oskari** [comment]
Hi,

I hope this is not an issue with minified code - when not minified, startup certainly takes time.
We're considering status messaging in general e.g. in context of accessing slow WFS services.
Jani

**Comment by ZakarFin** [comment]
Closing the issue as there doesn't seem to be much enthusiasm about this functionality. After 1.37 there are lifecycle events available so this is just missing a UI. Events include:
- "bundle.start" when bundle has been started
- "bundle.err" when failed to start a bundle
- "app.start" when all bundles in startup sequence has been started.

Listening to these are done like this:
Oskari.on(<event name as string>, function(event) {
   // handler for event
});
