### ISSUE TITLE
regarding geostats

### ISSUE THREAD

**Issue by simogeo** [nls-oskari/oskari#16]
Hi,

I'm the main [geostats](https://github.com/simogeo/geostats) developer. First of all, I'm glad to see that you use the library for oskari project.

I've seen the oskari project currently uses the v0.6 version. I let you know that today, the v 0.9 is available.

Moreover jenks.util.js file is not useful anymore. Please let me know if you get any trouble using geostats.

Regards,

**Comment by ZakarFin** [comment]
Updated to 1.5.0
