### ISSUE TITLE
character encoding problem when persisting marker data Oskari.mapframework.mapmodule.MarkersPlugin

### ISSUE THREAD

**Issue by iluwatar** [nls-oskari/oskari#18]
Steps to reproduce:

Enable the Oskari.mapframework.mapmodule.MarkersPlugin so you can add add markers on the map. Add a new marker with name "tässä". Then refresh the browser with F5 and the name of the marker has changed to something like "tÅ¤ssÅ¤".

**Comment by ZakarFin** [comment]
The problem was with cookie decoding on the server side. This commit fixes the issue: https://github.com/nls-oskari/oskari-server/commit/91676a5

Thanks for submitting the issue!
