### ISSUE TITLE
Licensing and governance

### ISSUE THREAD

**Issue by 7o9** [nls-oskari/oskari#2]
Apparently there is no indication whatsoever which license is used to disseminate this project. It may well be that I am just too blind to find it but then this will also happen to others. 

If you are still working out the details please feel free to contact me. I strongly advise to go for a regular license and not come up with something self made, probably a revised BSD would be a good fit - but you would have to check the libraries you are using for compatibility. 

Then you will have to add the license as a LICENSE.TXT to the root of your code and reference it at least from core.js and ideally all files worth mentioning. 

Re governance, if you are interested to get this project endorsed by a legal entitylater on you should make sure that you have the names and contacts of all contributors and get some kind of CLA in place to which anybody contributing code should agree to. 

Sorry for all the boring nitty gritty details but if you don't do them now they'll fire back later on. 

Maybe break this issue down into smaller tasks.

**Comment by ZakarFin** [comment]
CLA added: 
* https://github.com/nls-oskari/oskari/blob/master/CLA.txt
* http://oskari.org/documentation/development/license
