### ISSUE TITLE
Frontend development in Oskari

### ISSUE THREAD

**Issue by mfarook** [nls-oskari/oskari#32]
Is there any step by step documentation or examples for creating an application using Oskari framework from the scratch? How to add a base map, layer programmatically? How to add a new toolbar? How to add a new functionality using oskari?

**Comment by ZakarFin** [comment]
If you have the toolbar module/bundle part of your app and want to use another toolbar, you can use this request: http://oskari.org/api/requests#1.39.0/ui/toolbar/request/Toolbar.ToolbarRequest.md The toolbar module/bundle provides basic toolbar functionality: https://github.com/nls-oskari/oskari/tree/master/bundles/mapping/toolbar.

The database table oskari_maplayer holds information about layers that have been registered for use in Oskari. You can also register a layer in frontend only. For this you need to provide a JSON presentation of a layer and register it into MapLayerService. After that you can add it to map using AddMapLayerRequest. Here's an example from the my places functionality: https://github.com/nls-oskari/oskari/blob/master/bundles/framework/myplaces2/CategoryHandler.js#L145

Frontend functionality is added by creating bundles (modules) to provide a functionality for an application. An application consists of set of these bundles that are started in sequence in the browser. Here's a quick tutorial http://oskari.org/guides/quick-start/my-first-bundle. For the server there are multiple ways of adding functionality like hooking into existing functionalities to provide more integrations or creating something completely new. If you take a look at the site http://oskari.org/ you might be able to narrow down to some more specific question.

**Comment by ZakarFin** [comment]
You can also interact with Openlayers directly when adding layers so there's a bunch of options. It's more about what you are doing and if the layers should be manageable via the admin UI etc.

**Comment by mfarook** [comment]
This looks great and useful. Thank you so much.
